name: flutter_native_ocr
description: "A Flutter plugin for native OCR (Optical Character Recognition) using Apple's Vision framework on iOS and Google ML Kit on Android."
version: 0.1.0
homepage: https://github.com/shrawank039/flutter_native_ocr
repository: https://github.com/shrawank039/flutter_native_ocr
issue_tracker: https://github.com/shrawank039/flutter_native_ocr/issues
documentation: https://github.com/shrawank039/flutter_native_ocr#readme
topics:
  - ocr
  - vision
  - ios
  - android
  - text-recognition
  - apple-vision
  - google-mlkit

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterNativeOcrPlugin
      android:
        package: com.matrixdeveloper.flutter_native_ocr
        pluginClass: FlutterNativeOcrPlugin
